# The URL the site will be built for
base_url = "https://juninaba.github.io"

title = "Junichi Inaba"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# theme = "apollo"
# theme = "no-style-please"
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
logo = "images/my-notion-face.png"

# theme = "toggle"
# favicon = "./content/profile.jpg"
# socials = [
#   { name = "twitter", url = "https://x.com/JunInaba1", icon = "twitter" },
#   { name = "github", url = "https://github.com/juninaba", icon = "github" },
# ]
# menu = [
#   { name = "/posts", url = "/posts", weight = 1 },
#   { name = "/tags", url = "/tags", weight = 2 },
# ]
