# The URL the site will be built for
base_url = "https://juninaba.github.io"

title = "Junichi Inaba's Blog"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "apollo"
taxonomies = [{ name = "tags" }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

[extra]
# Put all your custom variables here
theme = "toggle"
# favicon = "/icon/favicon.png"
socials = [
  # Configure socials here
  { name = "twitter", url = "https://x.com/JunInaba1", icon = "twitter" },
  { name = "github", url = "https://github.com/juninaba", icon = "github" },
]
menu = [
  # Configure menu bar here
  { name = "/posts", url = "/posts", weight = 1 },
]
